package main

var elmTemplate = `
{{- with .Record -}}
module {{.Name}} exposing ({{.Name}}, decoder, encode)

import Json.Decode as D
import Json.Decode.Pipeline as P
import Json.Encode as E


-- Generated by https://github.com/jhillyerd/go-to-elm-json


type alias {{.Name}} =
{{- range $index, $el := .Fields }}
    {{ if $index }},{{ else }}{{"{"}}{{ end }} {{ .ElmName }} : {{ .ElmType.Name -}}
{{end}}
    {{"}"}}
{{- end}}
{{- range .Nested}}


type alias {{.Name}} =
{{- range $index, $el := .Fields }}
    {{ if $index }},{{ else }}{{"{"}}{{ end }} {{ .ElmName }} : {{ .ElmType.Name -}}
{{end}}
    {{"}"}}
{{- end}}


{{with .Record -}}
decoder : D.Decoder {{.Name}}
decoder =
    D.succeed {{.Name}}
{{- range .Fields }}
        |> P.required "{{ .JSONName }}" {{ .ElmType.Decoder "D" -}}
{{end}}


encode : {{.Name}} -> E.Value
encode r =
    E.object
{{- range $index, $el := .Fields }}
        {{ if $index }},{{ else }}[{{ end }} ("{{ .JSONName }}", {{ .ElmType.Encoder "E" }} r.{{ .ElmName }})
{{- end}}
        ]
{{- end}}
{{- range .Nested}}


{{.Decoder "D" }} : D.Decoder {{.Name}}
{{.Decoder "D" }} =
    D.succeed {{.Name}}
{{- range .Fields }}
        |> P.required "{{ .JSONName }}" {{ .ElmType.Decoder "D" -}}
{{end}}


{{.Encoder "E" }} : {{.Name}} -> E.Value
{{.Encoder "E" }} r =
    E.object
{{- range $index, $el := .Fields }}
        {{ if $index }},{{ else }}[{{ end }} ("{{ .JSONName }}", {{ .ElmType.Encoder "E" }} r.{{ .ElmName }})
{{- end}}
        ]
{{- end}}
`
